version: "2.1"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080