version: "2.1"

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DBConn: postgres://postgres:postgres@db/backend?sslmode=disable

  db:
    ports:
      - 5432:5432
    image: postgres:12
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres